### ISSUE TITLE
'Cannot read property replace of undefined' when trying to run

### ISSUE THREAD

**Issue by redby** [sanmont/vscode-kickass-studio#18]
Hi, 

I wanted to test your extension, because it looks very interesting to me, but I wasn't able to execute my code. When I hit CTRL+F5 and select KickAssembler studio then I got this error. 

'Cannot read property replace of undefined'

I believe I have everything set, because other KickAssembler extensions works fine.

**Comment by sanmont** [comment]
Hi redby, Ill try to debug it this weekend, im also pushing some new features that needs publishing.
A couple of questions first:
1. Which system are you using?  linux, windows?
2. can you post the sample code that fails?

**Comment by redby** [comment]
Hi,

It is quite strange. I tried to install extension on another computer and seems to be working almost as expected. I only have one problem to set breakpoint.  When I set breakpoint and then run debug it doesn't stop at breakpoint. 

I am using windows version 
My code is realy simple

*=$1000

Entry:
    inc $d020    
    jmp Entry

**Comment by redby** [comment]
![image](https://user-images.githubusercontent.com/2405004/89062962-a9acfc80-d367-11ea-9ba5-53476c6563c7.png)

Placing breakpoint

![image](https://user-images.githubusercontent.com/2405004/89063082-d5c87d80-d367-11ea-9c4e-0312d3c8c679.png)

Executing app

**Comment by redby** [comment]
![image](https://user-images.githubusercontent.com/2405004/89063209-07d9df80-d368-11ea-9362-907b7a7cf27e.png)

![image](https://user-images.githubusercontent.com/2405004/89063246-19bb8280-d368-11ea-8ae2-c868096af7ec.png)

**Comment by sanmont** [comment]
Hi @redby , I just publish a new version of the extension. I had those problems and I think i fixed them with this. I havent test it in 
windows so I cannot be 100% sure. Im developing it in linux.

Also look at readme,md that I added a new feature, the ability to format watches , so take a look at that.

Please let me know in about an hour if the problem is fixed, otherwise I need to debug it in a windows machine, Im guessing over next weekend.

**Comment by redby** [comment]
Hi @sanmont, unfortunatelly it looks that problem still persits in my setup. The breakpoint is still ignored.

**Comment by sanmont** [comment]
hey @redby  you have correctly configured these values?
![image](https://user-images.githubusercontent.com/35506206/89227560-cf3f3d80-d5d5-11ea-898a-f71c9fb27fbc.png)

**Comment by redby** [comment]
![image](https://user-images.githubusercontent.com/2405004/89227912-d28af700-d5de-11ea-9f52-a35e1d7b86ad.png)
 
Everything is working except setting breakpoint. I also gave a quick test to new feature and it is working. BTW: great idea. It is really helpfull.

**Comment by sanmont** [comment]
So you cant set breakpoints before it starts running?
For what you are telling me you were able to watch variables, so Im guessing pausing and setting breakpoints after you launch the program works.

Im guessing this is a windows thing, dont worry, Ill let you know if I have any news regarding this, luckily ill fix it by the weekend.

**Comment by redby** [comment]
Exactly as you are saying. I am not able to set breakpoint before it starts running. I can pause it and then I can watch variables. When I am paused I can not still set breakpoint. 

I wish you good bug hunt.

**Comment by sanmont** [comment]
Also, can you tell me which version of vice are you using? 
Just to make sure that is not a problem with the version.

**Comment by redby** [comment]
Currently I am using GTK3 version of VICE 3.4. I was also thinking that different version could be reason. I tried also native Windows version of VICE 3.2 and get same result.

Now I have working extension on two systems. Both of them are running WIN 10 and Java 8. Everything is working except setting breakpoints.

**Comment by sanmont** [comment]
@redby  Im still working on the bug, actually several bugs in windows. 
But I could reproduce the problem with breakpoints. Ill let you know when I finally fix it!
Thanks again for letting me know!

**Comment by sanmont** [comment]
@redby  I've published a version fixing the windows issues! Let me know if everything works correctly. 
Thanks!

**Comment by sanmont** [comment]
It should be updated in a couple of hours

**Comment by redby** [comment]
Hi, it looks something is working, but I am still not able to set breakpoint. I set breakpoint, start debug and breakpoint turns to unverified state and execution doesn't stop. Am I supposed to do some extra setup?

**Comment by redby** [comment]
One more observation which I found. When I use .break command in my code it also doesn't work. So far I didn't found how to use vice with breakpoints. It is working with C64Debugger, but not in Vice. Do you plan use of C64Debugger in future?

**Comment by sanmont** [comment]
Hi, @redby this sucks...  :-( 

When Im developing the extension that functionality works, but trying the packaged extension from the extension store it doesnt!!
![debugging](https://user-images.githubusercontent.com/35506206/89707598-91407180-d967-11ea-9f2e-fdec5c144d28.gif)

The idea is that you can use vscode normally for debugging and take advantage of that like using the watches, format them with what you need, using conditional breakpoints , as for  C64Debugger is my last priority because there is not much integration to do with vscode but just launch it.

Ill continue on debugging .

**Comment by sanmont** [comment]
ok @redby  now is properly fixed, I mistankenly published an old version. Also now follow definition and references works in windows as well. 
Let me now if now is working for you

**Comment by redby** [comment]
Hi @sanmont now it is working perfectly. I am able to set breakpoint without any issues. Finally I will be able to debug my code as I am used to debug on PC. Thank you. Keep your great work.
